name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose up -d

  safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Safety and Run Scan
        run: |
          pip install safety
          safety scan --key ${{secrets.SAFETY_API_KEY}}
      
      - name: Upload Safety Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: safety-scan-results
          path: safety-report.txt   
          

      - name: Pyraider
        run: |
          pip install pyraider
          pyraider check -f environment/app/web/requirements.txt > logs/result-pyraider.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result-pyraider.txt

