name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose up -d
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety check > logs/safety-report.txt || true
         
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/safety-report.txt
  sast:
    needs: [build, sca]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        
      - run: |
          mkdir -p logs/      
      
      - uses: jpetrucciani/bandit-check@master
        with:
          path: 'vuln_django_play/vuln_django'
          bandit_flags: '-lll -r -o logs/output.json -f json'
    
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/output.json        
  dast:
    needs: [build, sca]
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
    
     - name: Build Image for testing
       run: docker-compose up -d
 
     - name: ZAP Scan
       uses: zaproxy/action-baseline@v0.12.0
       with:
         target: 'http://localhost:8020/polls/'
         cmd_options: '-a'          
  

