name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose up -d
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety check > logs/safety-report.txt || true
         
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/safety-report.txt
          
      - name: Pyraider
        run: |
          pip install pyraider
          pyraider go  > logs/result-pyraider.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result-pyraider.txt
   

