name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose up -d
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   
      
      - run: |
          mkdir -p logs/
      - name: Safety
        run: |
         pip install safety
         safety scan
      - uses: actions/upload-artifact@v2
        with:
          api-key: ${{ secrets.dff069b7-f9fb-4bba-a20e-627b81f37330	 }}
          name: logs
          path: logs/result-safety.txt   
          

      - name: Pyraider
        run: |
          pip install pyraider
          pyraider check -f environment/app/web/requirements.txt > logs/result-pyraider.txt
          
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/result-pyraider.txt

