name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose -f ./environment/app/docker-compose.yml up --build -d
